/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.techest.schoolpaper;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bg0=0x7f020000;
        public static final int bg1=0x7f020001;
        public static final int bg2=0x7f020002;
        public static final int bg3=0x7f020003;
        public static final int bg4=0x7f020004;
        public static final int bg5=0x7f020005;
        public static final int logo=0x7f020006;
        public static final int overlay0=0x7f020007;
        public static final int overlay1=0x7f020008;
        public static final int overlay2=0x7f020009;
        public static final int overlay3=0x7f02000a;
        public static final int overlay4=0x7f02000b;
        public static final int overlay5=0x7f02000c;
        public static final int paper0=0x7f02000d;
    }
    public static final class id {
        public static final int cc2=0x7f05000b;
        public static final int date=0x7f050009;
        public static final int infoBar=0x7f050006;
        public static final int my_map=0x7f050001;
        public static final int quan=0x7f050005;
        public static final int render_map=0x7f050002;
        public static final int search=0x7f050003;
        public static final int searchtext=0x7f050004;
        public static final int thumb=0x7f05000c;
        public static final int title=0x7f050008;
        public static final int tv=0x7f050000;
        public static final int widget46=0x7f050007;
        public static final int widget80=0x7f05000a;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int mapview=0x7f030001;
        public static final int paperview=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
